[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "supermarket-receipt"
version = "0.0.1"
description = "Supermarket Receipt Kata"
requires-python = ">=3.7"

[tool.setuptools.packages.find]
where = ["src"] 