name: Tests TP3

on:
  push:
    paths:
      - 'Tp_Matin/TP3/bibliotheque_projet/**'
  pull_request:
    paths:
      - 'Tp_Matin/TP3/bibliotheque_projet/**'

jobs:
  test-tp3:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Tp_Matin/TP3/bibliotheque_projet

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Generate coverage
      run: pytest --cov=src/bibliotheque --cov-report=term
